[build]
  base = "client"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

# Auto deploy on every push to main
[context.production]
  command = "npm install && npm run build"

[context.branch-deploy]
  command = "npm install && npm run build"

[[redirects]]
  from = "https://www.malipeddisekhar.me/*"
  to = "https://malipeddisekhar.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
